name: CI/CD for .NET 8.0 Core App to GCP App Engine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    
      # Step 1: Checkout the code
      - name: Checkout code
        run: git clone https://github.com/${{ github.repository }} 

      # Step 2: Set up .NET SDK
      - name: Install .NET 8.0 SDK
        run: |
          wget https://packages.microsoft.com/config/ubuntu/22.04/prod.list
          sudo mv prod.list /etc/apt/sources.list.d/dotnetdev.list
          wget https://packages.microsoft.com/keys/microsoft.asc
          sudo apt-key add microsoft.asc
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
          dotnet --version

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      - name: List files for debugging
        run: ls -lrta

      # Step 4: Build the application
      - name: Build the application
        run:  dotnet build inventory.csproj --configuration Release

      # Step 5: Run tests (Optional step, add if you have unit tests)
      - name: Run tests
        run: dotnet test --configuration Release

      # Step 6: Publish the application
      - name: Publish the application
        run: dotnet publish inventory.csproj --configuration Release --output ./publish

      # Step 7: Set up Google Cloud authentication
      - name: Set up Google Cloud Authentication
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file /tmp/gcp-key.json
          gcloud config set project teak-environs-445405-g2
          
          

      # Step 8: Deploy to GCP App Engine
      - name: Deploy to Google Cloud App Engine
        run: |
          gcloud app browse || true  # Optional: Verify if App Engine is reachable
          gcloud app deploy ./publish/app.yaml --quiet 